"""
EcoTrace Backend API
====================

Purpose
-------
This backend implements the consumer search pipeline for EcoTrace.

Consumer flow
-------------
The consumer flow is query_id based:
- Consumers do not need to log in.
- Each valid search creates exactly one search_query record.
- The backend returns query_id to the frontend.
- The report module can later use query_id to generate the risk report.

Supported frontend inputs
-------------------------
Only ONE input type should be submitted per request:
1. barcode   -> barcode_pipeline.py  (EAN-13 validation, OpenFoodFacts, GS1, ABR)
2. brand     -> brand_pipeline.py    (IP Australia Trademark, ABR)
3. company_or_abn -> ABR Web Services (inline in this file)

Pipeline design
---------------
Company name / ABN:
    User enters company name or ABN
    -> ABR Web Services lookup / verification
    -> return legal name, ABN, state, postcode, GST status, ABN status

Barcode (see barcode_pipeline.py):
    User scans / enters EAN-13 barcode
    -> EAN-13 checksum validation
    -> OpenFoodFacts product lookup (primary)
    -> GS1 Verified-by-GS1 lookup (fallback)
    -> brand / brand_owner extraction
    -> ABR name lookup using extracted brand_owner

Brand name (see brand_pipeline.py):
    User enters brand name
    -> IP Australia Trade Mark Search API
    -> extract legal owner with ranked trademark selection
    -> ABR name lookup using extracted legal owner

Not included in this file
-------------------------
Report generation is intentionally not implemented here. The report team can
use query_id and search_query records produced by this backend.

Main endpoint
-------------
POST /api/search

Version history
---------------
4.0.0 - barcode and brand logic moved to dedicated pipeline modules
3.0.0 - initial pipeline implementation
"""

import os
import re
import xml.etree.ElementTree as ET
from typing import Optional, Dict, Any, Tuple, List
from uuid import UUID

import requests
import psycopg2
from psycopg2.extras import RealDictCursor
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

# Pipeline modules — each input type has its own dedicated module.
from barcode_pipeline import run_barcode_phase
from brand_pipeline import run_brand_phase, get_ip_australia_access_token


# ============================================================
# Environment
# ============================================================

load_dotenv()


# ============================================================
# FastAPI App
# ============================================================

app = FastAPI(
    title="EcoTrace Backend API",
    version="4.0.0",
    description="""
EcoTrace consumer search API.

Pipeline modules:
- barcode_pipeline.py  : EAN-13 validation -> OpenFoodFacts -> GS1 -> ABR
- brand_pipeline.py    : IP Australia Trade Mark Search -> ABR

Every valid search creates a query_id and stores one search_query record.
"""
)


# ============================================================
# CORS
# ============================================================

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Replace with frontend deployment URL in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ============================================================
# Database
# ============================================================

def get_conn():
    """
    Create a PostgreSQL database connection.

    Required .env variables:
    - DB_HOST
    - DB_PORT
    - DB_NAME
    - DB_USER
    - DB_PASSWORD
    """
    return psycopg2.connect(
        host=os.getenv("DB_HOST", "localhost"),
        port=os.getenv("DB_PORT", "5432"),
        dbname=os.getenv("DB_NAME", "ecotrace"),
        user=os.getenv("DB_USER", "postgres"),
        password=os.getenv("DB_PASSWORD"),
        cursor_factory=RealDictCursor,
    )


def serialize_row(row):
    """
    Convert a database row into a JSON-safe dictionary.

    UUID values are converted to strings because UUID objects are not directly
    JSON serializable.
    """
    if row is None:
        return None
    return {k: str(v) if isinstance(v, UUID) else v for k, v in row.items()}


# ============================================================
# Request Models
# ============================================================

class SearchRequest(BaseModel):
    """
    Main frontend search request.

    Exactly one of barcode, brand, or company_or_abn should be provided.

    user_id is optional — anonymous consumers do not need an account.
    query_id is always generated by the backend for every valid search.

    Example requests:
        Barcode:      {"barcode": "9310055002440"}
        Brand:        {"brand": "Tim Tam"}
        Company/ABN:  {"company_or_abn": "Arnott's"}
        ABN number:   {"company_or_abn": "88000014675"}
    """
    user_id:        Optional[str] = None
    barcode:        Optional[str] = None
    brand:          Optional[str] = None
    company_or_abn: Optional[str] = None


class CreateUserRequest(BaseModel):
    """
    Development endpoint payload.
    Kept for backward compatibility; consumer searches do not require user_id.
    """
    email:     str
    user_type: str = "consumer"


# ============================================================
# Input Cleaning and Validation
# ============================================================

def clean_text(value: Optional[str]) -> Optional[str]:
    """Strip whitespace; normalise empty strings to None."""
    if value is None:
        return None
    value = value.strip()
    return value if value else None


def clean_abn(value: str) -> str:
    """Remove spaces from an ABN string (e.g. '12 345 678 901' -> '12345678901')."""
    return re.sub(r"\s+", "", value or "")


def is_abn(value: str) -> bool:
    """Return True if value is exactly 11 digits after whitespace removal."""
    return clean_abn(value).isdigit() and len(clean_abn(value)) == 11


def get_single_input_type(
    barcode:        Optional[str],
    brand:          Optional[str],
    company_or_abn: Optional[str],
) -> Tuple[str, str, str]:
    """
    Enforce exactly one input type per request.

    Returns (input_type, input_value, frontend_type) where:
    - input_type   matches the database search_query.input_type_enum value
    - input_value  is the cleaned string stored in search_query.input_value
    - frontend_type is returned to the frontend in the response

    Raises HTTP 400 when zero or more than one inputs are provided, or when
    the provided value fails basic format validation.
    """
    provided = []
    if barcode:        provided.append(("barcode",      barcode,        "barcode"))
    if brand:          provided.append(("brand_name",   brand,          "brand"))
    if company_or_abn: provided.append(("company_name", company_or_abn, "company_or_abn"))

    if len(provided) == 0:
        raise HTTPException(
            status_code=400,
            detail="Please provide exactly one input: barcode, brand, or company_or_abn.",
        )
    if len(provided) > 1:
        raise HTTPException(
            status_code=400,
            detail="Please submit only one input type per search.",
        )

    input_type, input_value, frontend_type = provided[0]

    # Barcode: delegate deep validation to barcode_pipeline (EAN-13 checksum).
    # Basic numeric check here just ensures we don't hit the pipeline with garbage.
    if input_type == "barcode":
        cleaned_bc = re.sub(r"[\s\-]", "", input_value)
        if not cleaned_bc.isdigit() or not (8 <= len(cleaned_bc) <= 14):
            raise HTTPException(
                status_code=400,
                detail="Invalid barcode. Must be 8-14 digits (EAN-8, EAN-13, ITF-14).",
            )

    if input_type == "brand_name" and len(input_value) < 2:
        raise HTTPException(
            status_code=400,
            detail="Brand name must contain at least 2 characters.",
        )

    if input_type == "company_name":
        cleaned = clean_abn(input_value)
        if cleaned.isdigit() and not is_abn(cleaned):
            raise HTTPException(status_code=400, detail="Invalid ABN. ABN must be 11 digits.")
        if not cleaned.isdigit() and len(input_value) < 2:
            raise HTTPException(
                status_code=400,
                detail="Company name must contain at least 2 characters.",
            )

    return input_type, input_value, frontend_type


# ============================================================
# search_query Lifecycle
# ============================================================

def create_search_query(
    cur,
    input_type:  str,
    input_value: str,
    user_id:     Optional[str] = None,
):
    """
    Insert a pending search_query record before executing any external API calls.

    This guarantees a query_id exists even if the pipeline partially fails.
    Status progresses: pending -> resolved | failed
    """
    cur.execute(
        """
        INSERT INTO search_query (user_id, input_type, input_value, resolution_status)
        VALUES (%s, %s, %s, 'pending')
        RETURNING query_id, submitted_at;
        """,
        (user_id, input_type, input_value),
    )
    return cur.fetchone()


def update_search_query(
    cur,
    query_id,
    status:              str,
    resolved_company_id: Optional[str] = None,
    resolved_brand_id:   Optional[str] = None,
    resolved_product_id: Optional[str] = None,
):
    """
    Update search_query resolution after the pipeline completes.
    Only 'resolved' and 'failed' are valid final statuses.
    """
    if status not in ("resolved", "failed"):
        status = "failed"

    cur.execute(
        """
        UPDATE search_query
        SET
            resolution_status   = %s,
            resolved_company_id = %s,
            resolved_brand_id   = %s,
            resolved_product_id = %s
        WHERE query_id = %s;
        """,
        (status, resolved_company_id, resolved_brand_id, resolved_product_id, query_id),
    )


# ============================================================
# ABR Web Services
# ============================================================
# The company/ABN pipeline is self-contained here because it uses a simple
# XML call with no OAuth or multi-step resolution.  The barcode and brand
# pipelines are more complex and live in their own modules.

def verify_abn_with_abr(abn: str) -> Dict[str, Any]:
    """
    Verify an ABN via ABR SearchByABNv202001.

    Required .env: ABR_GUID
    """
    guid = os.getenv("ABR_GUID")
    if not guid:
        return {"success": False, "source": "ABR", "message": "ABR_GUID missing in .env"}

    abn = clean_abn(abn)
    if not is_abn(abn):
        return {"success": False, "source": "ABR", "message": "ABN must be 11 digits"}

    url = "https://abr.business.gov.au/abrxmlsearch/AbrXmlSearch.asmx/SearchByABNv202001"
    params = {
        "searchString": abn,
        "includeHistoricalDetails": "N",
        "authenticationGuid": guid,
    }

    try:
        response = requests.get(url, params=params, timeout=15)
        response.raise_for_status()

        root = ET.fromstring(response.text)
        ns   = {"abr": "http://abr.business.gov.au/ABRXMLSearch/"}

        # Check for ABR-level XML error before parsing results.
        exception_node = root.find(".//abr:exception", ns)
        if exception_node is not None:
            desc = exception_node.find(".//abr:exceptionDescription", ns)
            return {"success": False, "source": "ABR",
                    "message": desc.text if desc is not None else "ABR returned an exception"}

        abn_node      = root.find(".//abr:identifierValue", ns)
        name_node     = root.find(".//abr:organisationName", ns)
        state_node    = root.find(".//abr:stateCode", ns)
        postcode_node = root.find(".//abr:postcode", ns)
        status_node   = root.find(".//abr:entityStatusCode", ns)
        gst_node      = root.find(".//abr:goodsAndServicesTax", ns)

        if abn_node is None:
            return {"success": False, "source": "ABR", "message": "ABN not found in ABR"}

        return {
            "success":       True,
            "source":        "ABR",
            "abn":           abn_node.text,
            "legal_name":    name_node.text if name_node is not None else None,
            "state":         state_node.text if state_node is not None else None,
            "postcode":      postcode_node.text if postcode_node is not None else None,
            "abn_status":    status_node.text if status_node is not None else None,
            "gst_registered": gst_node is not None,
            "verified":      True,
        }

    except requests.exceptions.Timeout:
        return {"success": False, "source": "ABR", "message": "ABR request timed out"}
    except requests.exceptions.RequestException as e:
        return {"success": False, "source": "ABR", "message": f"Network error: {e}"}
    except ET.ParseError as e:
        return {"success": False, "source": "ABR", "message": f"Invalid XML from ABR: {e}"}
    except Exception as e:
        return {"success": False, "source": "ABR", "message": f"Unexpected error: {e}"}


def search_company_name_with_abr(company_name: str) -> Dict[str, Any]:
    """
    Search ABR by company / business name.

    Used by:
    - The company_name pipeline branch (direct user input)
    - barcode_pipeline.py  (passed as abr_lookup_fn)
    - brand_pipeline.py    (passed as abr_lookup_fn)

    Required .env: ABR_GUID
    """
    guid = os.getenv("ABR_GUID")
    if not guid:
        return {"success": False, "source": "ABR", "message": "ABR_GUID missing in .env"}

    if not company_name or len(company_name.strip()) < 2:
        return {"success": False, "source": "ABR", "message": "Company name is too short"}

    url = "https://abr.business.gov.au/abrxmlsearch/AbrXmlSearch.asmx/ABRSearchByNameAdvancedSimpleProtocol2017"
    params = {
        "name":               company_name.strip(),
        "postcode":           "",
        "legalName":          "Y",
        "tradingName":        "Y",
        "NSW": "Y", "SA": "Y", "ACT": "Y", "VIC": "Y",
        "WA":  "Y", "NT":  "Y", "QLD": "Y", "TAS": "Y",
        "authenticationGuid": guid,
    }

    try:
        response = requests.get(url, params=params, timeout=20)
        response.raise_for_status()

        root = ET.fromstring(response.text)
        ns   = {"abr": "http://abr.business.gov.au/ABRXMLSearch/"}

        # Check for ABR-level XML error.
        exception_node = root.find(".//abr:exception", ns)
        if exception_node is not None:
            desc = exception_node.find(".//abr:exceptionDescription", ns)
            return {"success": False, "source": "ABR",
                    "message": desc.text if desc is not None else "ABR returned an exception"}

        businesses = root.findall(".//abr:businessEntity", ns)
        if not businesses:
            return {"success": False, "source": "ABR", "message": "No company found in ABR"}

        # Collect all results and deduplicate by ABN.
        results = []
        seen_abns: set = set()
        for business in businesses:
            abn_node    = business.find(".//abr:identifierValue", ns)
            state_node  = business.find(".//abr:stateCode", ns)
            post_node   = business.find(".//abr:postcode", ns)
            status_node = business.find(".//abr:entityStatusCode", ns)
            abn_val     = abn_node.text if abn_node is not None else None

            if abn_val in seen_abns:
                continue
            seen_abns.add(abn_val)

            # Company name can be under organisationName or givenName/familyName.
            name_node = business.find(".//abr:organisationName", ns)
            if name_node is not None:
                legal_name = name_node.text
            else:
                given  = business.find(".//abr:givenName", ns)
                family = business.find(".//abr:familyName", ns)
                legal_name = " ".join(
                    filter(None, [
                        given.text if given is not None else None,
                        family.text if family is not None else None,
                    ])
                ) or company_name

            results.append({
                "abn":        abn_val,
                "legal_name": legal_name,
                "state":      state_node.text if state_node is not None else None,
                "postcode":   post_node.text if post_node is not None else None,
                "abn_status": status_node.text if status_node is not None else None,
                "verified":   abn_val is not None,
            })

        # Prefer an Active entity with a verified ABN.
        best = next(
            (r for r in results if r.get("abn_status") == "Active" and r["abn"]),
            results[0],
        )

        return {
            "success":     True,
            "source":      "ABR",
            **best,
            "best_match":  best,
            "all_results": results,
            "total":       len(results),
        }

    except requests.exceptions.Timeout:
        return {"success": False, "source": "ABR", "message": "ABR request timed out"}
    except requests.exceptions.RequestException as e:
        return {"success": False, "source": "ABR", "message": f"Network error: {e}"}
    except ET.ParseError as e:
        return {"success": False, "source": "ABR", "message": f"Invalid XML from ABR: {e}"}
    except Exception as e:
        return {"success": False, "source": "ABR", "message": f"Unexpected error: {e}"}


# ============================================================
# Basic Endpoints
# ============================================================

@app.get("/")
def root():
    return {
        "message":       "EcoTrace backend is running",
        "main_endpoint": "POST /api/search",
        "consumer_flow": "query_id based, no login required",
        "version":       "4.0.0",
    }


@app.get("/health")
def health():
    return {"status": "ok"}


# ============================================================
# Development User Endpoint
# ============================================================

@app.post("/api/users/test")
def create_test_user(payload: CreateUserRequest):
    """
    Create or reuse a test user.
    Kept for backward compatibility; the consumer pipeline does not require login.
    """
    conn = get_conn()
    cur  = conn.cursor()
    try:
        cur.execute(
            """
            INSERT INTO "user" (user_type, email)
            VALUES (%s, %s)
            ON CONFLICT (email) DO UPDATE SET email = EXCLUDED.email
            RETURNING user_id, user_type, email, created_at;
            """,
            (payload.user_type, payload.email),
        )
        user = cur.fetchone()
        conn.commit()
        return {"message": "User ready", "user": serialize_row(user)}
    except Exception as e:
        conn.rollback()
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        cur.close()
        conn.close()


# ============================================================
# Main Consumer Search Endpoint
# ============================================================

@app.post("/api/search")
def search_entity(payload: SearchRequest):
    """
    Main consumer search endpoint.

    Responsibilities
    ----------------
    1. Validate exactly one input is provided.
    2. Create a pending search_query record (returns query_id immediately).
    3. Dispatch to the appropriate pipeline module by input type.
    4. Update search_query to resolved / failed.
    5. Return a unified JSON response to the frontend.

    Input types and their pipelines
    --------------------------------
    barcode        -> barcode_pipeline.run_barcode_phase()
    brand_name     -> brand_pipeline.run_brand_phase()
    company_name   -> ABR inline (simple XML call, no dedicated module needed)
    """
    barcode        = clean_text(payload.barcode)
    brand          = clean_text(payload.brand)
    company_or_abn = clean_text(payload.company_or_abn)

    input_type, input_value, frontend_type = get_single_input_type(
        barcode, brand, company_or_abn
    )

    conn = get_conn()
    cur  = conn.cursor()

    try:
        query    = create_search_query(cur, input_type, input_value, payload.user_id)
        query_id = query["query_id"]

        pipeline_steps: List[str] = []
        result:         Dict[str, Any] = {}
        db_status = "failed"

        # ----------------------------------------------------
        # Branch 1 — Company name / ABN
        # Simple ABR lookup, no dedicated module needed.
        # ----------------------------------------------------
        if input_type == "company_name":
            if is_abn(company_or_abn):
                abn = clean_abn(company_or_abn)
                pipeline_steps.append("ABR ABN verification")
                abn_result = verify_abn_with_abr(abn)
                db_status  = "resolved" if abn_result.get("success") else "failed"
                result = {
                    "input_type":       "abn",
                    "input_value":      abn,
                    "status":           "external_resolved" if abn_result.get("success") else "not_found",
                    "source":           "ABR",
                    "company": {
                        "legal_name":    abn_result.get("legal_name"),
                        "abn":           abn_result.get("abn"),
                        "state":         abn_result.get("state"),
                        "postcode":      abn_result.get("postcode"),
                        "abn_status":    abn_result.get("abn_status"),
                        "gst_registered": abn_result.get("gst_registered"),
                    },
                    "abn_verification": abn_result,
                    "confidence":       95 if abn_result.get("success") else 0,
                }
            else:
                pipeline_steps.append("ABR company name search")
                abr_result = search_company_name_with_abr(company_or_abn)
                db_status  = "resolved" if abr_result.get("success") else "failed"
                result = {
                    "input_type":       "company_name",
                    "input_value":      company_or_abn,
                    "status":           "external_resolved" if abr_result.get("success") else "not_found",
                    "source":           "ABR",
                    "company": {
                        "legal_name":  abr_result.get("legal_name"),
                        "abn":         abr_result.get("abn"),
                        "state":       abr_result.get("state"),
                        "postcode":    abr_result.get("postcode"),
                        "abn_status":  abr_result.get("abn_status"),
                    },
                    "abn_verification": abr_result,
                    "message":          abr_result.get("message"),
                    "confidence":       90 if abr_result.get("success") else 0,
                }

            update_search_query(cur, query_id, db_status)

        # ----------------------------------------------------
        # Branch 2 — Barcode
        # Delegated entirely to barcode_pipeline.py.
        # Flow: EAN-13 validate -> OpenFoodFacts -> GS1 fallback -> ABR
        # ----------------------------------------------------
        elif input_type == "barcode":
            barcode_result = run_barcode_phase(
                barcode,
                abr_lookup_fn=search_company_name_with_abr,
            )
            pipeline_steps = barcode_result.get("pipeline", [])
            db_status      = "resolved" if barcode_result["success"] else "failed"

            result = {
                "input_type":       "barcode",
                "input_value":      barcode,
                "status":           barcode_result.get("status", "not_found"),
                "source":           barcode_result.get("source"),
                "product":          barcode_result.get("product"),
                "brand_raw":        barcode_result.get("brand_raw"),
                "brand_clean":      barcode_result.get("brand_clean"),
                "brand_owner":      barcode_result.get("brand_owner"),
                "manufacturer":     barcode_result.get("manufacturer"),
                "abn_verification": barcode_result.get("abr"),
                "confidence":       barcode_result.get("confidence", 0),
                "errors":           barcode_result.get("errors", []),
                "message":          barcode_result.get("error"),
            }

            update_search_query(cur, query_id, db_status)

        # ----------------------------------------------------
        # Branch 3 — Brand name
        # Delegated entirely to brand_pipeline.py.
        # Flow: IP Australia Trade Mark Search -> extract owner -> ABR
        # ----------------------------------------------------
        elif input_type == "brand_name":
            brand_result   = run_brand_phase(
                brand,
                abr_lookup_fn=search_company_name_with_abr,
            )
            pipeline_steps = brand_result.get("pipeline", [])
            db_status      = "resolved" if brand_result["success"] else "failed"

            result = {
                "input_type":       "brand",
                "input_value":      brand,
                "status":           brand_result.get("status", "not_found"),
                "source":           "IP Australia Trade Mark + ABR",
                "brand_name":       brand,
                "trademark":        brand_result.get("trademark"),
                "legal_owner":      brand_result.get("legal_owner"),
                "abn_verification": brand_result.get("abr"),
                "confidence":       brand_result.get("confidence", 0),
                "errors":           brand_result.get("errors", []),
                "message":          brand_result.get("error"),
            }

            update_search_query(cur, query_id, db_status)

        conn.commit()

        return {
            "query_id":          str(query_id),
            "status":            "success",
            "input_type":        frontend_type,
            "input_value":       input_value,
            "resolution_status": db_status,
            "pipeline_steps":    pipeline_steps,
            "result":            result,
        }

    except HTTPException:
        conn.rollback()
        raise
    except Exception as e:
        conn.rollback()
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        cur.close()
        conn.close()


# ============================================================
# Standalone Test Endpoints
# ============================================================

@app.get("/api/abn/verify/{abn}")
def verify_abn(abn: str):
    """Verify a single ABN directly via ABR. Example: GET /api/abn/verify/88000014675"""
    if not is_abn(abn):
        raise HTTPException(status_code=400, detail="ABN must be 11 digits")
    return verify_abn_with_abr(abn)


@app.get("/api/company/search/{company_name}")
def lookup_company_name(company_name: str):
    """Search a company name via ABR. Example: GET /api/company/search/Coles"""
    cleaned = clean_text(company_name)
    if not cleaned or len(cleaned) < 2:
        raise HTTPException(status_code=400, detail="Company name must be at least 2 characters")
    return search_company_name_with_abr(cleaned)


@app.get("/api/barcode/{barcode}")
def lookup_barcode(barcode: str):
    """
    Run the full barcode pipeline directly (EAN-13 -> OpenFoodFacts -> GS1 -> ABR).
    Example: GET /api/barcode/9310055002440
    """
    return run_barcode_phase(barcode, abr_lookup_fn=search_company_name_with_abr)


@app.get("/api/trademark/token-test")
def test_ip_australia_token():
    """Check that IP Australia OAuth credentials are working."""
    token = get_ip_australia_access_token()
    if not token:
        return {"status": "error", "message": "Unable to obtain token — check IP_AUSTRALIA_CLIENT_ID and IP_AUSTRALIA_CLIENT_SECRET"}
    return {"status": "success", "token_preview": token[:20] + "..."}


@app.get("/api/trademark/search/{brand}")
def lookup_trademark(brand: str):
    """
    Run the full brand pipeline directly (IP Australia Trade Mark -> ABR).
    Example: GET /api/trademark/search/TimTam
    """
    cleaned = clean_text(brand)
    if not cleaned or len(cleaned) < 2:
        raise HTTPException(status_code=400, detail="Brand must be at least 2 characters")
    return run_brand_phase(cleaned, abr_lookup_fn=search_company_name_with_abr)


# ============================================================
# Search History
# ============================================================

@app.get("/api/search/history/{user_id}")
def get_search_history(user_id: str):
    """Return search history for a given user_id, ordered newest first."""
    conn = get_conn()
    cur  = conn.cursor()
    try:
        cur.execute(
            """
            SELECT query_id, input_type, input_value, resolution_status,
                   resolved_company_id, resolved_brand_id, resolved_product_id, submitted_at
            FROM search_query
            WHERE user_id = %s
            ORDER BY submitted_at DESC;
            """,
            (user_id,),
        )
        rows = cur.fetchall()
        return {"user_id": user_id, "history": [serialize_row(r) for r in rows]}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        cur.close()
        conn.close()


@app.get("/api/search/query/{query_id}")
def get_search_query(query_id: str):
    """Retrieve a single search_query record by query_id."""
    conn = get_conn()
    cur  = conn.cursor()
    try:
        cur.execute(
            """
            SELECT query_id, user_id, input_type, input_value, resolution_status,
                   resolved_company_id, resolved_brand_id, resolved_product_id, submitted_at
            FROM search_query
            WHERE query_id = %s;
            """,
            (query_id,),
        )
        row = cur.fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="Query not found")
        return {"query": serialize_row(row)}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        cur.close()
        conn.close()
